### ISSUE TITLE
How to declare that BinRead needs to skip a certain amount of bytes?

### ISSUE THREAD

**Issue by Nimmerwoner** [jam1garner/binread#21]
I'm parsing a format that I have not defined myself nor control, so I cannot change it. Several times, the specification has "reserved" large amounts of bytes that currently serve no purpose. In the cases where it was a few `u32`s I just included a superfluous field in my struct definition, but I feel there must be a better way.

To illustrate, this is what I mean:
```rust
#[derive(BinRead)]
struct Environment {
    emissivity: f32,
    object_distance: f32,

    empty_space: [u8; 4],  // Example of intentionally superfluous variable. Occurs only once in this example, but multiple times in the real code 

    relative_humidity: f32,

    //empty_space5: [u128; 40],  // Example where above solution doesn't work 

    #[br(offset = 648)]  // Example of what I'm looking for: a way to instruct to skip the next 648 bytes
    planck_o: f32,
    planck_r2: i32,
}
```

Above I included as an example `#[br(offset = 648)]`. The idea is that it seeks forward with the given offset before reading the next value. Is something like this already possible?

**Comment by kitlith** [comment]
so, offset is already an attribute that does stuff with FilePtr, so you can say that a pointer is relative to a given offset.

It sounds like what you're looking for is pad_before/pad_after, or even seek_before: https://docs.rs/binread/1.1.1/binread/attribute/index.html#padding-and-alignment

**Comment by Nimmerwoner** [comment]
Thanks, that's exactly what I need. I also couldn't find the documentation of attributes, which is why I asked here, so thanks for the docs link as well!
