### ISSUE TITLE
Error is not Sync/Send

### ISSUE THREAD

**Issue by jerry73204** [jam1garner/binread#25]
The `Error` type contains `Box<dyn Any>` fields that drop `Send` and `Sync` traits. It makes the trait less compatible with multi-threaded programs. The concerned fields are `found` and `err` according to the [doc](https://docs.rs/binread/1.4.0/binread/error/enum.Error.html). They are simple enough to have those traits. Perhaps we can change it to `Box<dyn Any + Sync + Send>`?

**Comment by jam1garner** [comment]
Sounds like a good idea. I'd accept a PR if you're in a rush, otherwise I'll try to get to this soon

**Comment by jerry73204** [comment]
Here comes a PR. Please take a look.

**Comment by endrin** [comment]
I'd like to add that missing Sync/Send makes the crate incompatible with `anyhow` and `eyre`. Here's a minimal failing example:
```rust
use binread::{BinRead, BinReaderExt};

#[derive(BinRead, Debug)]
struct OneByte(u8);

fn parse() -> anyhow::Result<OneByte> {
    Ok(std::io::Cursor::new(b"0x01").read_ne::<OneByte>()?)
}
```

This fails to compile with the following error:

> `(dyn Any + 'static)` cannot be shared between threads safely
>   = help: the trait `Sync` is not implemented for `(dyn Any + 'static)`

**Comment by jam1garner** [comment]
Much appreciated input from both of you. @endrin if this doesn't fix anyhow/eyre compatibility, could you open another issue? Thanks!

**Comment by endrin** [comment]
This fixed anyhow interop, my example above compiles now. Thanks!
