### ISSUE TITLE
Error `pos` field type is too small for some targets

### ISSUE THREAD

**Issue by csnover** [jam1garner/binread#29]
Since positions are stream positions, `pos` fields should have `u64` type, but currently have `usize` type. binread is always using `as` to cast `u64` to `usize` internally, which means that those positions will be silently truncated on targets where `size_of::<usize>() < size_of::<u64>()` and `pos > usize::MAX` (e.g. reading from a file stream >4GiB on a 32-bit system). If there is some reason for `pos` to remain `usize`, fallible `try_from/try_into` should probably be used to panic at runtime if a value is out of range instead of truncating.

**Comment by jam1garner** [comment]
Agreed. Currently moving from binread to binrw, so I will try and include that change, thanks for pointing it out.

**Comment by jam1garner** [comment]
I'll go ahead and backport the fix since it's simple enough

**Comment by csnover** [comment]
Thanks! Sorry I didn’t have the time to send in a PR, hopefully I will be able to fix a couple things myself as I continue to work with binread. Looking forward to the enhanced functionality in binrw!
