### ISSUE TITLE
Assert statements on enum variants appear to not be parsed

### ISSUE THREAD

**Issue by BenHall-7** [jam1garner/binread#3]
In order to parse an enum, usually I import an argument to use as the discriminant number from a higher level struct. At first I didn't realize this wasn't being handled correctly on my own project because my enum variants were all of equal size. This caused issues on a different struct however, which led me to finding this. Here's a minimal reproducible example:

```rust
use binread::BinRead;

#[derive(BinRead)]
pub enum MyEnum {
    #[br(assert(size == 1))]
    U8(u8),
    #[br(assert(true))]
    U16(u16),
    #[br(assert(qwertyuiop))]
    U32(u32),
}
```

In short, these statements don't end up making their way into the expanded code

**Comment by jam1garner** [comment]
Ok so it looks like the problem isn't in parsing, it's in codegen.

On this line (in between `#body` and `Ok(#build_variant)`) is where the variant assertions need to be inserted:

https://github.com/jam1garner/binread_derive/blob/23537c4bc2e134e770fe5abb5ceaa103d4fa64b2/src/codegen/read_options.rs#L135

If you copy/paste this line here (and rename to `variant_assertion`):

https://github.com/jam1garner/binread_derive/blob/23537c4bc2e134e770fe5abb5ceaa103d4fa64b2/src/codegen/read_options.rs#L178

And then unwrap the assertions like here:

https://github.com/jam1garner/binread_derive/blob/23537c4bc2e134e770fe5abb5ceaa103d4fa64b2/src/codegen/read_options.rs#L196-L198

Then it should just work. I don't see anything that would require special-casing for the handling of enums, it seems like I structured the code for exactly this and just forgot to actually use the generalized code for enums as well (only structs).

**Comment by BenHall-7** [comment]
So since `tla` returns info about the whole enum instead of variants, this ends up putting the assert statements about the whole enum into each variant's parsing function.

Furthermore, one might expect a top-level assert statement to appear elsewhere, after the variant functions, but that doesn't appear to be so. However I'm not sure what the expected behavior or use cases of an assert statement on an enum would be

**Comment by BenHall-7** [comment]
Progress: `merge_tlas` simply left out the attributes on the variant and as a result this was skipped. Fixed here: https://github.com/jam1garner/binread_derive/pull/3

Will close the issue when it's merged

**Comment by jam1garner** [comment]
Fixed
