### ISSUE TITLE
How to specify Vec length from offset till EOF?

### ISSUE THREAD

**Issue by murlakatamenka** [jam1garner/binread#36]
I have a file with a magic and encrypted chunk that spans from magic till EOF, I struggle to express it with `BinRead`:

```rust
const MAGIC_LEN: u8 = 22;

#[derive(BinRead)]
#[br(magic = b"SOME_MAGIC")]
struct Foo {
   #[br(offset = MAGIC_LEN, count = <file_size> - MAGIC_LEN - 1]
   encrypted_chunk: Vec<u8>,
}
```

Struct is created via `Foo::read(std::fs::File::open("file_path")?)?`. 
How can this be achieved? Thanks in advance.

**Comment by jam1garner** [comment]
I would recommend a custom parser that uses `Read::read_to_end` internally

https://doc.rust-lang.org/std/io/trait.Read.html#method.read_to_end

https://docs.rs/binread/1.4.1/binread/attribute/index.html#custom-parsers

**Comment by murlakatamenka** [comment]
Thanks, I'll look into it.

**Comment by jam1garner** [comment]
@murlakatamenka an official solution has been added in the latest version in the form of [`until_eof`](https://docs.rs/binread/2.2.0/binread/fn.until_eof.html)

**Comment by murlakatamenka** [comment]
Cool, thanks for implementing this!
