### ISSUE TITLE
Any plans for supporting packed binary data?

### ISSUE THREAD

**Issue by Apanatshka** [jam1garner/binread#7]
I'm mostly familiar with packed binary data from header of network protocols (from a CS course that I took years ago, so I don't remember the details). Something like a byte contains two bits of flags and 6 bits of an unsigned integer. I'd love to be able to write:

```rust
struct UnpackedData {
    #[bits(1)]
    first_flag : bool,
    #[bits(1)]
    second_flag : bool,
    #[bits(6)]
    the_number : u8,
}
```

This is just a sketch obviously, I have no idea what would be the best attribute design. I imagine something like direction within the byte is important to specify? Or maybe there's only one sensible way depending on the endianness? (I imagine endianness becomes important when you want to read bits across a byte boundary). You probably want a "skip to next byte offset after this" attribute too to easily ignore some bits of padding.

**Comment by jam1garner** [comment]
It’s definitely possible and something I’ve thought about, but it’s definitely a massive undertaking. Even trying to draw up a design for it was something I found to be a bit difficult. Currently a lot of the inner-workings attempt to keep each field in the struct entirely independent and ignorant of each other as that reduces the implementation cost of each attribute. Trying to apply this to bit-level parsing has proven to be quite difficult, however the best approach I have thought of so far is having earlier fields store “leftover” data in a bit queue and future bit fields will use and, once exhausted, will then read more bytes from the reader.

As a temporary workaround it’s definitely possible to use parse_with and manually handle it with bitwise operations, however the limitation of byte-alignment will persist and is by no means a limitation I will ever try and fix as byte-unaligned parsing is too niche a use case for the how difficult it’d be to support.

Now, as to whether I plan on adding this? In the future perhaps, however I am only one person with a job and other (more popular, from what I can tell) projects. Larger additions don’t exactly feel personally achievable, however I’m willing to provide any help/guidance/mentorship needed to anyone looking to contribute.

**Comment by sharksforarms** [comment]
Feel free to inspire from deku if you'd like! https://github.com/sharksforarms/deku

**Comment by jam1garner** [comment]
@Apanatshka It's not 100% the best solution, however I just added an example of how to (rather easily, I think) use `modular_bitfield` to accomplish this task in a way that is solid for most use cases.

The use cases it doesn't support well (I think) are when the bitfields themselves have properties that BinRead is designed to make easier (for example mayyyybe an encoding with a more-complex variable number of bits?). However, if the data containing the bitfields is "basic" (i.e. it's just a dumb copy into a bitfield struct for the same code in C), then it should work here.

The example of how to do bitfields is here: https://docs.rs/binread/1.4.0/binread/attribute/index.html#map-for-bitfields

**Comment by jam1garner** [comment]
```rust
use modular_bitfield::prelude::*;

#[derive(BinRead)]
struct Packet {
    header: PackedData,
    
    #[br(if(header.is_fast)]
    speed: Option<u32>,
  
    #[br(if(header.status == 3)]
    body: Option<Body>,
}

// The following field is a single byte read from the Reader
#[bitfield]
#[derive(BinRead)]
#[br(map = Self::from_bytes)]
pub struct PackedData {
    status: B4,
    is_fast: bool,
    is_static: bool,
    is_alive: bool,
    is_good: bool,
}
 
// example byte: 0x53
// [good] [alive] [static] [fast] [status]
//   0       1       0       1      0011
//
//  false  true    false    true     3
``

Oh also here's an example I threw together for how it could be useful for packet-style parsing.
